services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    networks:
      - shared-net
    ports:
      - 8086:8081
    volumes:
      - nexus-data:/nexus-data

networks:
  shared-net:
    name: shared-net

volumes:
  nexus-data:
