spring.application.name=${SPRING_APPLICATION_NAME:MEDIA-SERVICE}

server.port=${SERVER_PORT:8083}

#MongoDb
# spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27019/mediadb}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongodb_media:27017/mediadb}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:mediadb}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

#Minio
minio.url=${MINIO_URL:http://localhost:9000}
minio.publicUrl=${MINIO_PUBLIC_URL}
minio.access.name=${MINIO_ACCESS_NAME:minio}
minio.access.secret=${MINIO_ACCESS_SECRET:change-me}
minio.bucket.name=${MINIO_BUCKET:buy01-media}


spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Kafka Connection
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
# spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:media-service-group}
spring.kafka.consumer.auto-offset-reset=earliest

# Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value Deserializer (Safety Wrapper)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.properties.spring.json.value.default.type=com.buy01.media.dto.ProductEvent

media.orphan.max-age-minutes=1
media.orphan-cleanup.fixed-rate-ms=60000
