spring.application.name=ORDER-SERVICE
server.port=8084

# MongoDB
# spring.data.mongodb.uri=${ORDER_MONGODB_URI:mongodb://localhost:27020/ordersdb}
spring.data.mongodb.uri=${ORDER_MONGODB_URI:mongodb://mongodb_orders:27017/ordersdb}
spring.data.mongodb.database=${ORDER_MONGODB_DATABASE:ordersdb}


# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Kafka Connection
# spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:order-service-group}

spring.kafka.consumer.auto-offset-reset=earliest

# Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value Deserializer (Safety Wrapper)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# logging.level.org.springframework.kafka=DEBUG
# logging.level.org.apache.kafka=DEBUG

############## 
spring.kafka.consumer.properties.spring.json.value.default.type=com.buy01.orders.dtos.ProductEvent