# Server
server.port=${SERVER_PORT:8082}

# Application
spring.application.name=${SPRING_APPLICATION_NAME:PRODUCT-SERVICE}

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27018/productdb
# spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongodb_products:27017/productdb}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:productdb}

# JWT
jwt.secret=${JWT_SECRET:your-256-bit-secret-key-here-change-in-prod}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Actuator 
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}


# kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
# spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.consumer.group-id=product-service-group
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:debug-group}
spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.bootstrap-servers: localhost:9092
# spring.kafka.consumer.properties.reconnect.backoff.ms: 5000
# spring.kafka.consumer.properties.reconnect.backoff.max.ms: 30000
spring.kafka.producer.retries: ${SPRING_KAFKA_PRODUCER_RETRIES:3}



logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG